### ISSUE TITLE
[Help Wanted] Config SWC compiler with PostCSS, Tailwind and custom alias

### ISSUE THREAD

**Issue by RodrigoTomeES** [Karibash/storybook-addon-swc#10]
Hi,

First of all thanks for your work!,

I have configurated Storybook to use it with PostCSS, Tailwind, custom alias and webpack 5, but now I want to move to SWC. I am tried to configurate it removing Webpack 5 and adding the SWC plugin, but I am reciving a error with PostCSS. Could you help me?

Here is my OLD configuration:

```js
const path = require('path');
const aliasConfig = require('../tsconfig.json');
const pathsNext = aliasConfig.compilerOptions.paths || {};

function getPaths(paths) {
  const pathsSB = {};
  const keys = Object.keys(paths);

  keys.forEach(function (key) {
    const alias = key.replace('/*', '');
    const pathNext = `../${paths[key][0].replace('*', '')}`;

    pathsSB[alias] = path.resolve(__dirname, pathNext);
  });

  return pathsSB;
}

module.exports = {
  webpackFinal: async (config, { configType }) => {
    config.resolve.modules = [path.resolve(__dirname, '..'), 'node_modules'];
    config.resolve.alias = {
      ...config.resolve.alias,
      ...getPaths(pathsNext),
    };
    return config;
  },
  stories: [
    '../components/**/*.stories.mdx',
    '../components/**/*.stories.@(js|jsx|ts|tsx)',
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    {
      /**
       * Fix Storybook issue with PostCSS@8
       * @see https://github.com/storybookjs/storybook/issues/12668#issuecomment-773958085
       *
       * Fix Storybook issue with CSS Module and PostCSS
       * @see https://github.com/storybookjs/addon-postcss/issues/29
       */
      name: '@storybook/addon-postcss',
      options: {
        styleLoaderOptions: {},
        cssLoaderOptions: {
          modules: true,
          sourceMap: true,
          importLoaders: 1,
        },
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
  ],
  staticDirs: ['../public', '../assets', '../stories/assets'],
  framework: '@storybook/react',
  core: {
    builder: 'webpack5',
  },
};
```

Here is my NEW configuration, removed core with Webpack 5 and added SWC plugin:

```js
const path = require('path');
const aliasConfig = require('../tsconfig.json');
const pathsNext = aliasConfig.compilerOptions.paths || {};

function getPaths(paths) {
  const pathsSB = {};
  const keys = Object.keys(paths);

  keys.forEach(function (key) {
    const alias = key.replace('/*', '');
    const pathNext = `../${paths[key][0].replace('*', '')}`;

    pathsSB[alias] = path.resolve(__dirname, pathNext);
  });

  return pathsSB;
}

module.exports = {
  webpackFinal: async (config, { configType }) => {
    config.resolve.modules = [path.resolve(__dirname, '..'), 'node_modules'];
    config.resolve.alias = {
      ...config.resolve.alias,
      ...getPaths(pathsNext),
    };
    return config;
  },
  stories: [
    '../components/**/*.stories.mdx',
    '../components/**/*.stories.@(js|jsx|ts|tsx)',
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    {
      /**
       * Fix Storybook issue with PostCSS@8
       * @see https://github.com/storybookjs/storybook/issues/12668#issuecomment-773958085
       *
       * Fix Storybook issue with CSS Module and PostCSS
       * @see https://github.com/storybookjs/addon-postcss/issues/29
       */
      name: '@storybook/addon-postcss',
      options: {
        styleLoaderOptions: {},
        cssLoaderOptions: {
          modules: true,
          sourceMap: true,
          importLoaders: 1,
        },
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
    'storybook-addon-swc',
  ],
  staticDirs: ['../public', '../assets', '../stories/assets'],
  framework: '@storybook/react',
};
```

As I said before I tried to change the builder to SWC, removing core and added the SWC plugin. In the error message I see that Storybook said I am using Webpack 4, maybe I have a bad config. Here is the error: 

```bash
yarn run v1.22.17
$ start-storybook -p 6006
info @storybook/react v6.4.13
info 
info => Loading presets
info => Serving static files from ././public at /
info => Serving static files from ././assets at /
info => Serving static files from ././stories/assets at /
info => Loading custom manager config
info => Using PostCSS preset with postcss@8.4.5
info => Using default Webpack4 setup
info => Loading custom manager config
14% building 34/36 modules 2 active .../project-name/node_modules/@storybook/builder-webpack4/node_modules/webpack/buildin/module.js
info => Using cached manager
webpack built preview 086ae59b40b8b63edbce in 5673ms
✖ ｢wdm｣: Hash: 086ae59b40b8b63edbce
Version: webpack 4.46.0
Time: 5673ms
Built at: 22/03/2022 12:02:17
                    Asset      Size  Chunks                          Chunk Names
       0.iframe.bundle.js   225 KiB       0  [emitted]               
   0.iframe.bundle.js.map   215 KiB       0  [emitted] [dev]         
       1.iframe.bundle.js   186 KiB       1  [emitted]               
   1.iframe.bundle.js.map  88.4 KiB       1  [emitted] [dev]         
       2.iframe.bundle.js  68.5 KiB       2  [emitted]               
   2.iframe.bundle.js.map  53.4 KiB       2  [emitted] [dev]         
       3.iframe.bundle.js  9.14 KiB       3  [emitted]               
   3.iframe.bundle.js.map  6.47 KiB       3  [emitted] [dev]         
       4.iframe.bundle.js  62.1 KiB       4  [emitted]               
   4.iframe.bundle.js.map  48.5 KiB       4  [emitted] [dev]         
       5.iframe.bundle.js   372 KiB       5  [emitted]        [big]  
   5.iframe.bundle.js.map   412 KiB       5  [emitted] [dev]         
       6.iframe.bundle.js  15.7 KiB       6  [emitted]               
   6.iframe.bundle.js.map  16.6 KiB       6  [emitted] [dev]         
              iframe.html  11.7 KiB          [emitted]               
    main.iframe.bundle.js  7.84 MiB    main  [emitted]        [big]  main
main.iframe.bundle.js.map  6.53 MiB    main  [emitted] [dev]         main
Entrypoint main [big] = main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js 208 bytes {main} [built]
[./.storybook/preview.js-generated-config-entry.js] 3.63 KiB {main} [built]
[./generated-stories-entry.js] 674 bytes {main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js] 2.99 KiB {main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3 KiB {main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3 KiB {main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js] 3 KiB {main} [built]
[./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js] 3.04 KiB {main} [built]
[./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-config-entry.js] 3.04 KiB {main} [built]
[./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3 KiB {main} [built]
[./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3 KiB {main} [built]
[./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js] 3 KiB {main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js] 97 bytes {main} [built]
[./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js] 2.99 KiB {main} [built]
    + 1695 hidden modules

ERROR in ./styles/storybook.css (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./styles/storybook.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/user-name/Sites/project-name/node_modules/postcss-loader/dist/index.js:40:24)
 @ ./styles/storybook.css (./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./styles/storybook.css) 2:26-136 53:4-74:5 56:18-128
 @ ./.storybook/preview.js
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.27 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 2.04 KiB {HtmlWebpackPlugin_0} [built]
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/user-name/Sites/project-name/node_modules/postcss-loader/dist/index.js:40:24)
    at /Users/user-name/Sites/project-name/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/user-name/Sites/project-name/node_modules/@storybook/builder-webpack4/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/user-name/Sites/project-name/node_modules/@storybook/builder-webpack4/node_modules/loader-runner/lib/LoaderRunner.js:233:18

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**System**

```bash
Environment Info:

  System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.3.1/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Firefox: 98.0.1
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.4.13 => 6.4.13 
    @storybook/addon-docs: ^6.4.13 => 6.4.18 
    @storybook/addon-essentials: ^6.4.13 => 6.4.13 
    @storybook/addon-links: ^6.4.13 => 6.4.13 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/builder-webpack5: ^6.4.13 => 6.4.13 
    @storybook/manager-webpack5: ^6.4.13 => 6.4.13 
    @storybook/react: ^6.4.13 => 6.4.13 
    storybook-addon-swc: ^1.1.1 => 1.1.1
```

**Comment by Karibash** [comment]
@RodrigoTomeES 

This add-on simply replaces the existing babel-loader with swc-loader, so there is no need to remove webpack5 from the builder options.
Could you please check it once, as I think it will work by simply adding storybook-addon-swc to the existing configuration as shown below?

```js
const path = require('path');
const aliasConfig = require('../tsconfig.json');
const pathsNext = aliasConfig.compilerOptions.paths || {};

function getPaths(paths) {
  const pathsSB = {};
  const keys = Object.keys(paths);

  keys.forEach(function (key) {
    const alias = key.replace('/*', '');
    const pathNext = `../${paths[key][0].replace('*', '')}`;

    pathsSB[alias] = path.resolve(__dirname, pathNext);
  });

  return pathsSB;
}

module.exports = {
  webpackFinal: async (config, { configType }) => {
    config.resolve.modules = [path.resolve(__dirname, '..'), 'node_modules'];
    config.resolve.alias = {
      ...config.resolve.alias,
      ...getPaths(pathsNext),
    };
    return config;
  },
  stories: [
    '../components/**/*.stories.mdx',
    '../components/**/*.stories.@(js|jsx|ts|tsx)',
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    {
      /**
       * Fix Storybook issue with PostCSS@8
       * @see https://github.com/storybookjs/storybook/issues/12668#issuecomment-773958085
       *
       * Fix Storybook issue with CSS Module and PostCSS
       * @see https://github.com/storybookjs/addon-postcss/issues/29
       */
      name: '@storybook/addon-postcss',
      options: {
        styleLoaderOptions: {},
        cssLoaderOptions: {
          modules: true,
          sourceMap: true,
          importLoaders: 1,
        },
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
    'storybook-addon-swc', // Add this!
  ],
  staticDirs: ['../public', '../assets', '../stories/assets'],
  framework: '@storybook/react',
  core: {
    builder: 'webpack5',
  },
};
```

If the above steps do not solve the problem, it would be helpful if you could create a minimal repository where the problem can be reproduced.

**Comment by RodrigoTomeES** [comment]
@Karibash Hi, thanks for the quick response, with that configuration does it work. I tried it before but I didn't see any different between use it or not in load time so I thought it doesn't work 🙈

## With SWC
<img width="936" alt="imagen" src="https://user-images.githubusercontent.com/13077343/159477223-1d35433f-5c09-4b28-9ffc-cea8094dc124.png">

## With babel
<img width="1018" alt="imagen" src="https://user-images.githubusercontent.com/13077343/159477796-3a5b74f3-5f38-4f09-831f-59b37ba09a02.png">
<img width="917" alt="imagen" src="https://user-images.githubusercontent.com/13077343/159477832-071b55ba-4114-4958-9733-827ef2dd04bd.png">

**Comment by Karibash** [comment]
@RodrigoTomeES 

> @Karibash Hi, thanks for the quick response, with that configuration does it work. I tried it before but I didn't see any different between use it or not in load time so I thought it doesn't work 🙈

The storybook has a build cache mechanism, so if a cache exists, there may not be a noticeable difference in build speed.
If you build again after deleting the cache with the following command, you should see a change in build speed.

`rm -rf node_modules/.cache/storybook`

**Comment by RodrigoTomeES** [comment]
@Karibash thanks!, I think it improves at most about 0.5s in each build.

**Comment by Karibash** [comment]
@RodrigoTomeES 

We have added several example projects to show how to use the add-ons.
The example projects include a mechanism to dynamically generate components so that performance testing can be performed.

The following is the result of generating 50 components, switching add-on settings and building.  
Most of the time spent building is for modules for which no loader is specified, so there is no clear speedup, but there is a significant speedup in the process of typescript transpiling.

## with bebel-loader
<img width="330" alt="スクリーンショット 2022-03-23 14 04 54" src="https://user-images.githubusercontent.com/40270352/159628515-c96588e0-322d-4ffd-afac-cde7077ea6de.png">

## with swc-loader
<img width="331" alt="スクリーンショット 2022-03-23 14 08 01" src="https://user-images.githubusercontent.com/40270352/159628557-226dacfe-a398-4739-9449-581bbce7fb87.png">

**Comment by RodrigoTomeES** [comment]
@Karibash hi, thanks for the examples, I made also some test and I see that the most advantage of SWC is in compiler that is so much quickly but in HMR there isn't a big different.

## Babel Build
<img width="315" alt="Babel Build" src="https://user-images.githubusercontent.com/13077343/159657694-37f7170d-dbb9-4a25-8230-667af93ba780.png">

## SWC Build
<img width="312" alt="SWC Build" src="https://user-images.githubusercontent.com/13077343/159657780-a8e9439c-4b0d-49e9-9164-ce05238b665f.png">

## Babel HMR
<img width="330" alt="Babel HMR First Build" src="https://user-images.githubusercontent.com/13077343/159657835-10ea2680-d02b-4db7-8c78-4e3a3d19dc74.png">
<img width="678" alt="Babel HMR Builds" src="https://user-images.githubusercontent.com/13077343/159657824-f4262367-67e9-430e-af56-f5d2eaac2b6c.png">

## SWC HMR
<img width="320" alt="SWC HMR First Build" src="https://user-images.githubusercontent.com/13077343/159657899-26612236-81d3-4d1f-8301-ee78126c0764.png">
<img width="691" alt="SWC HMR Builds" src="https://user-images.githubusercontent.com/13077343/159657888-75cfbcfa-7693-41ac-a362-e28205fe3677.png">

**Comment by Karibash** [comment]
@RodrigoTomeES 

From your build results, it looks like the postcss-loader is the biggest bottleneck.
Since the ability to bundle css files with swc has not been released yet, I don't think this add-on can do anything about it.
https://github.com/swc-project/swc/issues/3900#issuecomment-1060704590

I think it would be better to wait for swc to officially release the css bundle or try add-ons that use esbuild, vite, etc.
esbuild: https://github.com/pocka/storybook-addon-turbo-build
vite: https://github.com/eirslett/storybook-builder-vite

**Comment by RodrigoTomeES** [comment]
@Karibash Thank you very much for the advice I will look at the options you have told me

**Comment by Karibash** [comment]
@RodrigoTomeES 
Thank you for your time in our discussion.
I have added the alternative proposal to README.md.
https://github.com/Karibash/storybook-addon-swc#-alternative

**Comment by RodrigoTomeES** [comment]
@Karibash Thank you for all the help! 🤗

I saw the alternative proposal and I think there is a bug here, I think you wanted to put storybook-addon-turbo-build but I am not pretty sure.

![imagen](https://user-images.githubusercontent.com/13077343/159953336-022d2f84-ebaa-4408-92c6-b845c691b49a.png)

**Comment by Karibash** [comment]
@RodrigoTomeES 
Thank you for pointing out the typo.
I was using a machine translation and did not notice the error. 😥
I fixed the typo. I am not very confident in writing English, so it would be helpful if you could take a look.
https://github.com/Karibash/storybook-addon-swc/pull/18/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R70

**Comment by RodrigoTomeES** [comment]
@Karibash nothing! English is not my forte but I saw the new text and it look good for me 👌

**Comment by Karibash** [comment]
@RodrigoTomeES Thanks for your help! 🥳
